import type { Config } from 'tailwindcss';
import tokens from './design-tokens.json';

// ---------------------------------------------------------------------------
// Tailwind theme built FROM design-tokens.json (ADR-0007).
//
// RULES enforced here:
//   - theme.extend consumes ONLY values read from `tokens`. No literal hex,
//     px, or rem appears below — every value traces back to the locked token
//     file. (scripts/token-audit.sh additionally guards src/ against stray
//     literals.)
//   - LIGHT MODE ONLY for v1. The `color.dark` token set is intentionally
//     present in design-tokens.json but is NOT wired here — no `darkMode`
//     strategy, no `dark:` variant generation, no doubled theme.
//     // dark mode deferred to post-v1 (see ADR-0007 / tokens color.dark).
//     When dark ships, add `darkMode: ['class', '[data-theme="dark"]']` and
//     map a second CSS-variable layer to `tokens.color.dark`.
//
// ACCESSIBILITY OVERRIDE (approved, see design-tokens components.button):
//   amber and success ("approve") buttons MUST use dark `ink` text, NOT white.
//   White-on-amber (2.1:1) and white-on-green fail WCAG AA. The token below
//   `colors.onAccent` exposes ink for that purpose; the Button primitive
//   (Phase 2, owned by implementer) must consume `text-ink` on amber/success,
//   never `text-white`. Do NOT build the Button here.
// ---------------------------------------------------------------------------

// Colours are wired to CSS variables (var(--c-<path>)) defined in
// src/index.theme.css (generated by scripts/gen-theme-css.cjs from
// tokens.color.light / .dark). The variable layer switches on
// `:root[data-theme="dark"]`, so every colour utility below is theme-aware
// WITHOUT any `dark:` variant or component change (ADR-0007 dark-mode ship).
const type = tokens.typography;
const space = tokens.spacing;
const radius = tokens.radius;
const shadow = tokens.shadow;
const components = tokens.components;
const layout = tokens.layout;
const motion = tokens.motion;
const focus = tokens.focus;

// Component dimensions, traced straight to tokens so primitives never need a
// magic-number literal. Keys are semantic (avatar-*, control-*, nav, topbar,
// fab) and map to design-tokens.json components.*/layout.*.
const avatar = components.avatar.sizes;
const sizeScale: Record<string, string> = {
  'avatar-chip': avatar.chip,
  'avatar-default': avatar.default,
  'avatar-switcher': avatar.switcher,
  'avatar-author': avatar.author,
  'btn-sm': components.button.sizes.sm.height,
  'btn-md': components.button.sizes.md.height,
  'btn-lg': components.button.sizes.lg.height,
  field: components.textField.rowHeight,
  badge: components.badge.height,
  'badge-sm': components.badge.heightSm,
  topbar: layout.topBarHeight,
  nav: layout.bottomNavHeight,
  fab: layout.fab.size,
  backslot: layout.backSlotWidth,
};

// spacing keys in the token file are the raw px-step labels (plus _-prefixed
// meta keys we skip). Build a clean numeric-key scale for Tailwind, then add
// the named semantic spacings the layout chrome needs (e.g. the toast viewport
// sits a fixed distance above the bottom nav — spacing._semantic).
const spacingScale = {
  ...(Object.fromEntries(Object.entries(space).filter(([k]) => /^\d+$/.test(k))) as Record<
    string,
    string
  >),
  'toast-from-nav': space._semantic.toastFromBottomNav,
  'fab-from-bottom': space._semantic.fabFromBottom,
  'footer-from-bottom': space._semantic.footerFromBottom,
};

// typography sizes: map each named style to [size, { lineHeight, letterSpacing, fontWeight }]
const fontSize = Object.fromEntries(
  Object.entries(type.styles).map(([name, s]) => [
    name,
    [
      s.rem,
      {
        lineHeight: String(s.leading),
        letterSpacing: s.tracking,
        fontWeight: String(s.weight),
      },
    ],
  ]),
) as Config['theme'] extends { fontSize?: infer T } ? NonNullable<T> : never;

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  // Belt-and-suspenders for the category dot utilities. These are emitted from a
  // STATIC literal map (calendarService.eventTagDotClass / Badge.tsx TONE_CLASS),
  // so the JIT already sees them — the safelist guarantees they survive even if a
  // refactor ever obscures the literal. Each maps to a defined token-backed
  // colour (theme.colors.category.*-dot, traced to design-tokens.json).
  safelist: [
    'bg-category-school-dot',
    'bg-category-sports-dot',
    'bg-category-family-dot',
    'bg-category-work-dot',
  ],
  // dark mode deferred to post-v1 (see ADR-0007 / tokens color.dark). Light-only.
  theme: {
    extend: {
      colors: {
        // Every value is a CSS var from src/index.theme.css — theme-aware by
        // data-theme, no `dark:` variants needed. Var names are the kebab-cased
        // token paths (brand.indigoDark -> --c-brand-indigo-dark).
        brand: {
          DEFAULT: 'var(--c-brand-indigo)',
          dark: 'var(--c-brand-indigo-dark)',
          light: 'var(--c-brand-indigo-light)',
          on: 'var(--c-brand-on-indigo)',
        },
        // Accent (amber). NOTE: on-accent text is INK, not white (a11y override).
        accent: {
          DEFAULT: 'var(--c-accent-amber)',
          light: 'var(--c-accent-amber-light)',
          dark: 'var(--c-accent-amber-dark)',
        },
        // Approved a11y override: ink text used on amber + success fills.
        onAccent: 'var(--c-text-ink)',
        // Surfaces
        surface: {
          bg: 'var(--c-surface-bg)',
          card: 'var(--c-surface-card)',
          line: 'var(--c-surface-line)',
          line2: 'var(--c-surface-line2)',
          scrim: 'var(--c-surface-scrim)',
        },
        // Text / ink
        ink: {
          DEFAULT: 'var(--c-text-ink)',
          2: 'var(--c-text-ink2)',
          mute: 'var(--c-text-mute)',
          mute2: 'var(--c-text-mute2)',
          'on-dark': 'var(--c-text-on-dark)',
        },
        // Event categories (signal only, paired with a label/icon — never decorative)
        category: {
          'school-dot': 'var(--c-category-school-dot)',
          'school-bg': 'var(--c-category-school-bg)',
          'school-text': 'var(--c-category-school-text)',
          'sports-dot': 'var(--c-category-sports-dot)',
          'sports-bg': 'var(--c-category-sports-bg)',
          'sports-text': 'var(--c-category-sports-text)',
          'family-dot': 'var(--c-category-family-dot)',
          'family-bg': 'var(--c-category-family-bg)',
          'family-text': 'var(--c-category-family-text)',
          'work-dot': 'var(--c-category-work-dot)',
          'work-bg': 'var(--c-category-work-bg)',
          'work-text': 'var(--c-category-work-text)',
        },
        // Status
        status: {
          ok: 'var(--c-status-ok)',
          'ok-light': 'var(--c-status-ok-light)',
          'ok-text': 'var(--c-status-ok-text)',
          warn: 'var(--c-status-warn)',
          'warn-light': 'var(--c-status-warn-light)',
          'warn-text': 'var(--c-status-warn-text)',
          info: 'var(--c-status-info)',
          'info-light': 'var(--c-status-info-light)',
          'info-text': 'var(--c-status-info-text)',
          danger: 'var(--c-status-danger)',
          'danger-light': 'var(--c-status-danger-light)',
          'danger-text': 'var(--c-status-danger-text)',
        },
      },
      fontFamily: {
        sans: type.family.sans.split(',').map((s) => s.trim()),
        display: type.family.display.split(',').map((s) => s.trim()),
        mono: type.family.mono.split(',').map((s) => s.trim()),
      },
      fontSize,
      fontWeight: {
        medium: String(type.weight.medium),
        semibold: String(type.weight.semibold),
        bold: String(type.weight.bold),
        extrabold: String(type.weight.extrabold),
      },
      spacing: spacingScale,
      borderRadius: {
        sm: radius.sm,
        md: radius.md,
        control: radius.control,
        card: radius.card,
        sheet: radius.sheet,
        full: radius.full,
      },
      boxShadow: {
        card: shadow.card,
        'brand-rest': shadow.brandElevatedRest,
        'brand-active': shadow.brandElevatedActive,
        sheet: shadow.sheet,
        toast: shadow.toast,
      },
      zIndex: Object.fromEntries(
        Object.entries(tokens.zIndex).map(([k, v]) => [k, String(v)]),
      ) as Record<string, string>,
      width: sizeScale,
      height: sizeScale,
      minHeight: {
        tap: tokens.touchTarget.min, // 44px — WCAG 2.5.5 minimum tap target
      },
      minWidth: {
        tap: tokens.touchTarget.min,
      },
      maxWidth: {
        app: layout.maxWidth,
        frame: layout.frameAbove,
      },
      ringWidth: {
        // focus.ringWidth token (3px) — the obvious focus-visible ring required
        // by AODA / WCAG 2.4.7 & 1.4.11 (>=3:1). See design-tokens.json focus.
        focus: focus.ringWidth,
      },
      ringColor: {
        // focus.ringColor token (== brand indigo). The focus-visible ring uses
        // `ring-brand` for colour across all primitives. The token's reference
        // shadow form uses 45% alpha; we render solid indigo, which exceeds the
        // token's alpha for contrast and still satisfies the >=3:1 floor — a
        // deliberate, documented simplification of the ring token. Wired to the
        // theme var so the ring lightens in dark mode (interaction.focusRing is
        // #3730A3 in light == the old focus.ringColor, #A5B4FC in dark).
        brand: 'var(--c-interaction-focus-ring)',
      },
      ringOffsetWidth: {
        focus: focus.ringOffset, // focus.ringOffset token (2px)
      },
      transitionTimingFunction: {
        out: motion.easing.out,
        sheet: motion.easing.sheet,
      },
      transitionDuration: {
        cardPress: motion.duration.cardPress,
        scrim: motion.duration.scrim,
        toast: motion.duration.toast,
        sheet: motion.duration.sheet,
      },
    },
  },
  plugins: [],
} satisfies Config;
